'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace portailsage
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SageDataServiceSoap", [Namespace]:="http://eurekify.com/webservices")>  _
    Partial Public Class SageDataService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private data_source_get_configurationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private data_source_get_auditcardsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private data_source_get_bprsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_databasesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_propertiesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private udb_get_usersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private rdb_get_resourcesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_rolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_configuration_usersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_configuration_resourcesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private database_get_fieldsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_user_role_linksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_user_resource_linksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_role_resource_linksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfg_get_role_role_linksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auditcard_get_alertsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private bpr_get_rulesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Rrq.Securite.GestionAcces.My.MySettings.Default.TS7N242_AccesSage_portailsage_SageDataService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event data_source_get_configurationsCompleted As data_source_get_configurationsCompletedEventHandler
        
        '''<remarks/>
        Public Event data_source_get_auditcardsCompleted As data_source_get_auditcardsCompletedEventHandler
        
        '''<remarks/>
        Public Event data_source_get_bprsCompleted As data_source_get_bprsCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_databasesCompleted As cfg_get_databasesCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_propertiesCompleted As cfg_get_propertiesCompletedEventHandler
        
        '''<remarks/>
        Public Event udb_get_usersCompleted As udb_get_usersCompletedEventHandler
        
        '''<remarks/>
        Public Event rdb_get_resourcesCompleted As rdb_get_resourcesCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_rolesCompleted As cfg_get_rolesCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_configuration_usersCompleted As cfg_get_configuration_usersCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_configuration_resourcesCompleted As cfg_get_configuration_resourcesCompletedEventHandler
        
        '''<remarks/>
        Public Event database_get_fieldsCompleted As database_get_fieldsCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_user_role_linksCompleted As cfg_get_user_role_linksCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_user_resource_linksCompleted As cfg_get_user_resource_linksCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_role_resource_linksCompleted As cfg_get_role_resource_linksCompletedEventHandler
        
        '''<remarks/>
        Public Event cfg_get_role_role_linksCompleted As cfg_get_role_role_linksCompletedEventHandler
        
        '''<remarks/>
        Public Event auditcard_get_alertsCompleted As auditcard_get_alertsCompletedEventHandler
        
        '''<remarks/>
        Public Event bpr_get_rulesCompleted As bpr_get_rulesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/data_source_get_configurations", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function data_source_get_configurations(ByVal server As String, ByVal database As String) As String
            Dim results() As Object = Me.Invoke("data_source_get_configurations", New Object() {server, database})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub data_source_get_configurationsAsync(ByVal server As String, ByVal database As String)
            Me.data_source_get_configurationsAsync(server, database, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub data_source_get_configurationsAsync(ByVal server As String, ByVal database As String, ByVal userState As Object)
            If (Me.data_source_get_configurationsOperationCompleted Is Nothing) Then
                Me.data_source_get_configurationsOperationCompleted = AddressOf Me.Ondata_source_get_configurationsOperationCompleted
            End If
            Me.InvokeAsync("data_source_get_configurations", New Object() {server, database}, Me.data_source_get_configurationsOperationCompleted, userState)
        End Sub
        
        Private Sub Ondata_source_get_configurationsOperationCompleted(ByVal arg As Object)
            If (Not (Me.data_source_get_configurationsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent data_source_get_configurationsCompleted(Me, New data_source_get_configurationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/data_source_get_auditcards", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function data_source_get_auditcards(ByVal server As String, ByVal database As String) As String
            Dim results() As Object = Me.Invoke("data_source_get_auditcards", New Object() {server, database})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub data_source_get_auditcardsAsync(ByVal server As String, ByVal database As String)
            Me.data_source_get_auditcardsAsync(server, database, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub data_source_get_auditcardsAsync(ByVal server As String, ByVal database As String, ByVal userState As Object)
            If (Me.data_source_get_auditcardsOperationCompleted Is Nothing) Then
                Me.data_source_get_auditcardsOperationCompleted = AddressOf Me.Ondata_source_get_auditcardsOperationCompleted
            End If
            Me.InvokeAsync("data_source_get_auditcards", New Object() {server, database}, Me.data_source_get_auditcardsOperationCompleted, userState)
        End Sub
        
        Private Sub Ondata_source_get_auditcardsOperationCompleted(ByVal arg As Object)
            If (Not (Me.data_source_get_auditcardsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent data_source_get_auditcardsCompleted(Me, New data_source_get_auditcardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/data_source_get_bprs", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function data_source_get_bprs(ByVal server As String, ByVal database As String) As String
            Dim results() As Object = Me.Invoke("data_source_get_bprs", New Object() {server, database})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub data_source_get_bprsAsync(ByVal server As String, ByVal database As String)
            Me.data_source_get_bprsAsync(server, database, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub data_source_get_bprsAsync(ByVal server As String, ByVal database As String, ByVal userState As Object)
            If (Me.data_source_get_bprsOperationCompleted Is Nothing) Then
                Me.data_source_get_bprsOperationCompleted = AddressOf Me.Ondata_source_get_bprsOperationCompleted
            End If
            Me.InvokeAsync("data_source_get_bprs", New Object() {server, database}, Me.data_source_get_bprsOperationCompleted, userState)
        End Sub
        
        Private Sub Ondata_source_get_bprsOperationCompleted(ByVal arg As Object)
            If (Not (Me.data_source_get_bprsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent data_source_get_bprsCompleted(Me, New data_source_get_bprsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_databases", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_databases(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_databases", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_databasesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_databasesAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_databasesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_databasesOperationCompleted Is Nothing) Then
                Me.cfg_get_databasesOperationCompleted = AddressOf Me.Oncfg_get_databasesOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_databases", New Object() {server, database, cfgName}, Me.cfg_get_databasesOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_databasesOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_databasesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_databasesCompleted(Me, New cfg_get_databasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_properties", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_properties(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_properties", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_propertiesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_propertiesAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_propertiesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_propertiesOperationCompleted Is Nothing) Then
                Me.cfg_get_propertiesOperationCompleted = AddressOf Me.Oncfg_get_propertiesOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_properties", New Object() {server, database, cfgName}, Me.cfg_get_propertiesOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_propertiesOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_propertiesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_propertiesCompleted(Me, New cfg_get_propertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/udb_get_users", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function udb_get_users(ByVal server As String, ByVal database As String, ByVal udbName As String) As String
            Dim results() As Object = Me.Invoke("udb_get_users", New Object() {server, database, udbName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub udb_get_usersAsync(ByVal server As String, ByVal database As String, ByVal udbName As String)
            Me.udb_get_usersAsync(server, database, udbName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub udb_get_usersAsync(ByVal server As String, ByVal database As String, ByVal udbName As String, ByVal userState As Object)
            If (Me.udb_get_usersOperationCompleted Is Nothing) Then
                Me.udb_get_usersOperationCompleted = AddressOf Me.Onudb_get_usersOperationCompleted
            End If
            Me.InvokeAsync("udb_get_users", New Object() {server, database, udbName}, Me.udb_get_usersOperationCompleted, userState)
        End Sub
        
        Private Sub Onudb_get_usersOperationCompleted(ByVal arg As Object)
            If (Not (Me.udb_get_usersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent udb_get_usersCompleted(Me, New udb_get_usersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/rdb_get_resources", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function rdb_get_resources(ByVal server As String, ByVal database As String, ByVal rdbName As String) As String
            Dim results() As Object = Me.Invoke("rdb_get_resources", New Object() {server, database, rdbName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub rdb_get_resourcesAsync(ByVal server As String, ByVal database As String, ByVal rdbName As String)
            Me.rdb_get_resourcesAsync(server, database, rdbName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub rdb_get_resourcesAsync(ByVal server As String, ByVal database As String, ByVal rdbName As String, ByVal userState As Object)
            If (Me.rdb_get_resourcesOperationCompleted Is Nothing) Then
                Me.rdb_get_resourcesOperationCompleted = AddressOf Me.Onrdb_get_resourcesOperationCompleted
            End If
            Me.InvokeAsync("rdb_get_resources", New Object() {server, database, rdbName}, Me.rdb_get_resourcesOperationCompleted, userState)
        End Sub
        
        Private Sub Onrdb_get_resourcesOperationCompleted(ByVal arg As Object)
            If (Not (Me.rdb_get_resourcesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent rdb_get_resourcesCompleted(Me, New rdb_get_resourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_roles", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_roles(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_roles", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_rolesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_rolesAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_rolesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_rolesOperationCompleted Is Nothing) Then
                Me.cfg_get_rolesOperationCompleted = AddressOf Me.Oncfg_get_rolesOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_roles", New Object() {server, database, cfgName}, Me.cfg_get_rolesOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_rolesOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_rolesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_rolesCompleted(Me, New cfg_get_rolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_configuration_users", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_configuration_users(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_configuration_users", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_configuration_usersAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_configuration_usersAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_configuration_usersAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_configuration_usersOperationCompleted Is Nothing) Then
                Me.cfg_get_configuration_usersOperationCompleted = AddressOf Me.Oncfg_get_configuration_usersOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_configuration_users", New Object() {server, database, cfgName}, Me.cfg_get_configuration_usersOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_configuration_usersOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_configuration_usersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_configuration_usersCompleted(Me, New cfg_get_configuration_usersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_configuration_resources", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_configuration_resources(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_configuration_resources", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_configuration_resourcesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_configuration_resourcesAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_configuration_resourcesAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_configuration_resourcesOperationCompleted Is Nothing) Then
                Me.cfg_get_configuration_resourcesOperationCompleted = AddressOf Me.Oncfg_get_configuration_resourcesOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_configuration_resources", New Object() {server, database, cfgName}, Me.cfg_get_configuration_resourcesOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_configuration_resourcesOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_configuration_resourcesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_configuration_resourcesCompleted(Me, New cfg_get_configuration_resourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/database_get_fields", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function database_get_fields(ByVal server As String, ByVal database As String, ByVal dbName As String, ByVal dbType As String) As String
            Dim results() As Object = Me.Invoke("database_get_fields", New Object() {server, database, dbName, dbType})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub database_get_fieldsAsync(ByVal server As String, ByVal database As String, ByVal dbName As String, ByVal dbType As String)
            Me.database_get_fieldsAsync(server, database, dbName, dbType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub database_get_fieldsAsync(ByVal server As String, ByVal database As String, ByVal dbName As String, ByVal dbType As String, ByVal userState As Object)
            If (Me.database_get_fieldsOperationCompleted Is Nothing) Then
                Me.database_get_fieldsOperationCompleted = AddressOf Me.Ondatabase_get_fieldsOperationCompleted
            End If
            Me.InvokeAsync("database_get_fields", New Object() {server, database, dbName, dbType}, Me.database_get_fieldsOperationCompleted, userState)
        End Sub
        
        Private Sub Ondatabase_get_fieldsOperationCompleted(ByVal arg As Object)
            If (Not (Me.database_get_fieldsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent database_get_fieldsCompleted(Me, New database_get_fieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_user_role_links", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_user_role_links(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_user_role_links", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_user_role_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_user_role_linksAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_user_role_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_user_role_linksOperationCompleted Is Nothing) Then
                Me.cfg_get_user_role_linksOperationCompleted = AddressOf Me.Oncfg_get_user_role_linksOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_user_role_links", New Object() {server, database, cfgName}, Me.cfg_get_user_role_linksOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_user_role_linksOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_user_role_linksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_user_role_linksCompleted(Me, New cfg_get_user_role_linksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_user_resource_links", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_user_resource_links(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_user_resource_links", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_user_resource_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_user_resource_linksAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_user_resource_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_user_resource_linksOperationCompleted Is Nothing) Then
                Me.cfg_get_user_resource_linksOperationCompleted = AddressOf Me.Oncfg_get_user_resource_linksOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_user_resource_links", New Object() {server, database, cfgName}, Me.cfg_get_user_resource_linksOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_user_resource_linksOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_user_resource_linksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_user_resource_linksCompleted(Me, New cfg_get_user_resource_linksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_role_resource_links", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_role_resource_links(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_role_resource_links", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_role_resource_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_role_resource_linksAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_role_resource_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_role_resource_linksOperationCompleted Is Nothing) Then
                Me.cfg_get_role_resource_linksOperationCompleted = AddressOf Me.Oncfg_get_role_resource_linksOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_role_resource_links", New Object() {server, database, cfgName}, Me.cfg_get_role_resource_linksOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_role_resource_linksOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_role_resource_linksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_role_resource_linksCompleted(Me, New cfg_get_role_resource_linksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/cfg_get_role_role_links", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cfg_get_role_role_links(ByVal server As String, ByVal database As String, ByVal cfgName As String) As String
            Dim results() As Object = Me.Invoke("cfg_get_role_role_links", New Object() {server, database, cfgName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfg_get_role_role_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String)
            Me.cfg_get_role_role_linksAsync(server, database, cfgName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfg_get_role_role_linksAsync(ByVal server As String, ByVal database As String, ByVal cfgName As String, ByVal userState As Object)
            If (Me.cfg_get_role_role_linksOperationCompleted Is Nothing) Then
                Me.cfg_get_role_role_linksOperationCompleted = AddressOf Me.Oncfg_get_role_role_linksOperationCompleted
            End If
            Me.InvokeAsync("cfg_get_role_role_links", New Object() {server, database, cfgName}, Me.cfg_get_role_role_linksOperationCompleted, userState)
        End Sub
        
        Private Sub Oncfg_get_role_role_linksOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfg_get_role_role_linksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfg_get_role_role_linksCompleted(Me, New cfg_get_role_role_linksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/auditcard_get_alerts", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auditcard_get_alerts(ByVal server As String, ByVal database As String, ByVal auditCard As String) As String
            Dim results() As Object = Me.Invoke("auditcard_get_alerts", New Object() {server, database, auditCard})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auditcard_get_alertsAsync(ByVal server As String, ByVal database As String, ByVal auditCard As String)
            Me.auditcard_get_alertsAsync(server, database, auditCard, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auditcard_get_alertsAsync(ByVal server As String, ByVal database As String, ByVal auditCard As String, ByVal userState As Object)
            If (Me.auditcard_get_alertsOperationCompleted Is Nothing) Then
                Me.auditcard_get_alertsOperationCompleted = AddressOf Me.Onauditcard_get_alertsOperationCompleted
            End If
            Me.InvokeAsync("auditcard_get_alerts", New Object() {server, database, auditCard}, Me.auditcard_get_alertsOperationCompleted, userState)
        End Sub
        
        Private Sub Onauditcard_get_alertsOperationCompleted(ByVal arg As Object)
            If (Not (Me.auditcard_get_alertsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auditcard_get_alertsCompleted(Me, New auditcard_get_alertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/bpr_get_rules", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function bpr_get_rules(ByVal server As String, ByVal database As String, ByVal bpr As String) As String
            Dim results() As Object = Me.Invoke("bpr_get_rules", New Object() {server, database, bpr})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub bpr_get_rulesAsync(ByVal server As String, ByVal database As String, ByVal bpr As String)
            Me.bpr_get_rulesAsync(server, database, bpr, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub bpr_get_rulesAsync(ByVal server As String, ByVal database As String, ByVal bpr As String, ByVal userState As Object)
            If (Me.bpr_get_rulesOperationCompleted Is Nothing) Then
                Me.bpr_get_rulesOperationCompleted = AddressOf Me.Onbpr_get_rulesOperationCompleted
            End If
            Me.InvokeAsync("bpr_get_rules", New Object() {server, database, bpr}, Me.bpr_get_rulesOperationCompleted, userState)
        End Sub
        
        Private Sub Onbpr_get_rulesOperationCompleted(ByVal arg As Object)
            If (Not (Me.bpr_get_rulesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent bpr_get_rulesCompleted(Me, New bpr_get_rulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub data_source_get_configurationsCompletedEventHandler(ByVal sender As Object, ByVal e As data_source_get_configurationsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class data_source_get_configurationsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub data_source_get_auditcardsCompletedEventHandler(ByVal sender As Object, ByVal e As data_source_get_auditcardsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class data_source_get_auditcardsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub data_source_get_bprsCompletedEventHandler(ByVal sender As Object, ByVal e As data_source_get_bprsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class data_source_get_bprsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_databasesCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_databasesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_databasesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_propertiesCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_propertiesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_propertiesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub udb_get_usersCompletedEventHandler(ByVal sender As Object, ByVal e As udb_get_usersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class udb_get_usersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub rdb_get_resourcesCompletedEventHandler(ByVal sender As Object, ByVal e As rdb_get_resourcesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class rdb_get_resourcesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_rolesCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_rolesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_rolesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_configuration_usersCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_configuration_usersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_configuration_usersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_configuration_resourcesCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_configuration_resourcesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_configuration_resourcesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub database_get_fieldsCompletedEventHandler(ByVal sender As Object, ByVal e As database_get_fieldsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class database_get_fieldsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_user_role_linksCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_user_role_linksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_user_role_linksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_user_resource_linksCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_user_resource_linksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_user_resource_linksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_role_resource_linksCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_role_resource_linksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_role_resource_linksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub cfg_get_role_role_linksCompletedEventHandler(ByVal sender As Object, ByVal e As cfg_get_role_role_linksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfg_get_role_role_linksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub auditcard_get_alertsCompletedEventHandler(ByVal sender As Object, ByVal e As auditcard_get_alertsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auditcard_get_alertsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub bpr_get_rulesCompletedEventHandler(ByVal sender As Object, ByVal e As bpr_get_rulesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class bpr_get_rulesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
