'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TS7Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RRQ.web.ressources.TS7Messages", GetType(TS7Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun &lt;b&gt;nom&lt;/b&gt; ne correspond à votre recherche. Veuillez vérifier les informations et y apporter les corrections requises..
        '''</summary>
        Friend Shared ReadOnly Property TS70002E() As String
            Get
                Return ResourceManager.GetString("TS70002E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;unité administrative de la section &lt;b&gt;Autre unité administrative&lt;/b&gt; doit être différente de la principale. Veuillez modifier votre choix..
        '''</summary>
        Friend Shared ReadOnly Property TS70003E() As String
            Get
                Return ResourceManager.GetString("TS70003E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Les équipes de la section &lt;b&gt;Unité administrative principale&lt;/b&gt; doivent être différentes. Veuillez modifier votre choix..
        '''</summary>
        Friend Shared ReadOnly Property TS70004E() As String
            Get
                Return ResourceManager.GetString("TS70004E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous devez inscrire le &lt;b&gt;nom &lt;/b&gt;et/ou le &lt;b&gt;prénom&lt;/b&gt;  ou le &lt;b&gt;code utilisateur&lt;/b&gt;..
        '''</summary>
        Friend Shared ReadOnly Property TS70005E() As String
            Get
                Return ResourceManager.GetString("TS70005E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Les équipes de la section &lt;b&gt;Autre unité administrative&lt;/b&gt; doivent être différentes. Veuillez modifier votre choix..
        '''</summary>
        Friend Shared ReadOnly Property TS70007E() As String
            Get
                Return ResourceManager.GetString("TS70007E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Un {0} doit être sélectionné..
        '''</summary>
        Friend Shared ReadOnly Property TS70009E() As String
            Get
                Return ResourceManager.GetString("TS70009E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La date de &lt;b&gt;fin de contrat&lt;/b&gt; doit être supérieure à la date effective..
        '''</summary>
        Friend Shared ReadOnly Property TS70010E() As String
            Get
                Return ResourceManager.GetString("TS70010E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La demande d&apos;ajout des rôles de l&apos;employé {0} a été transmise avec succès..
        '''</summary>
        Friend Shared ReadOnly Property TS70011I() As String
            Get
                Return ResourceManager.GetString("TS70011I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La demande de modification des rôles de l&apos;employé {0}  a été transmise avec succès..
        '''</summary>
        Friend Shared ReadOnly Property TS70012I() As String
            Get
                Return ResourceManager.GetString("TS70012I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La demande de modification des accès au répertoire a été transmise avec succès. .
        '''</summary>
        Friend Shared ReadOnly Property TS70014I() As String
            Get
                Return ResourceManager.GetString("TS70014I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La prolongation d&apos;un rôle sert à la conserver au-delà de la date effective de la demande.  Veuillez corriger l&apos;une ou l&apos;autre des dates..
        '''</summary>
        Friend Shared ReadOnly Property TS70015E() As String
            Get
                Return ResourceManager.GetString("TS70015E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun changement apporté aux rôles de l&apos;employé, veuillez réviser ou attacher un fichier, inscrire un commentaire à la section Accès non couverts par les rôles..
        '''</summary>
        Friend Shared ReadOnly Property TS70017I() As String
            Get
                Return ResourceManager.GetString("TS70017I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une {0} doit être sélectionnée..
        '''</summary>
        Friend Shared ReadOnly Property TS70018E() As String
            Get
                Return ResourceManager.GetString("TS70018E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le format du champ &lt;b&gt;courriel&lt;/b&gt; est erroné. Utilisez le format «prénom».«nom»@rrq.gouv.qc.ca..
        '''</summary>
        Friend Shared ReadOnly Property TS70019E() As String
            Get
                Return ResourceManager.GetString("TS70019E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La &lt;b&gt;Date effective de la demande&lt;/b&gt; doit être supérieure ou égale à la date du jour..
        '''</summary>
        Friend Shared ReadOnly Property TS70020E() As String
            Get
                Return ResourceManager.GetString("TS70020E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;adresse de courriel existe déjà.  Une nouvelle adresse de courriel a été générée automatiquement pour cet employé..
        '''</summary>
        Friend Shared ReadOnly Property TS70021I() As String
            Get
                Return ResourceManager.GetString("TS70021I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun rôle sélectionné pour cet employé. Veuillez réviser ou attacher un fichier, inscrire un commentaire à la section Accès non couverts par les rôles..
        '''</summary>
        Friend Shared ReadOnly Property TS70022E() As String
            Get
                Return ResourceManager.GetString("TS70022E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le propriétaire du rôle sera avisé des demandes de prolongation des accès au-delà de 2 semaines..
        '''</summary>
        Friend Shared ReadOnly Property TS70023I() As String
            Get
                Return ResourceManager.GetString("TS70023I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection du rôle métier {0} nécessite la sélection d&apos;au moins une tâche correspondante..
        '''</summary>
        Friend Shared ReadOnly Property TS70024E() As String
            Get
                Return ResourceManager.GetString("TS70024E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection de la tâche {0} nécessite la sélection du rôle métier correspondant..
        '''</summary>
        Friend Shared ReadOnly Property TS70025E() As String
            Get
                Return ResourceManager.GetString("TS70025E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas sélectionner plus de cinq unités administratives..
        '''</summary>
        Friend Shared ReadOnly Property TS70026I() As String
            Get
                Return ResourceManager.GetString("TS70026I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le champ {0} doit être complété..
        '''</summary>
        Friend Shared ReadOnly Property TS70027E() As String
            Get
                Return ResourceManager.GetString("TS70027E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier auprès du demandeur si l&apos;employé fait partie d&apos;une des unités inscrites comme owner du rôle {0} et accorder le REO approprié si requis..
        '''</summary>
        Friend Shared ReadOnly Property TS70028I() As String
            Get
                Return ResourceManager.GetString("TS70028I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier auprès du demandeur si l&apos;employé fait partie d&apos;une des unités inscrites comme owner {0} et accorder les REO appropriés si requis..
        '''</summary>
        Friend Shared ReadOnly Property TS70029I() As String
            Get
                Return ResourceManager.GetString("TS70029I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier auprès du demandeur si l&apos;employé doit conserver les accès communs à tous les employés de l&apos;unité {0} même si aucun rôle pour cette unité ne sera assigné à l&apos;employé. Dans la négative, retirer le REO correspondant..
        '''</summary>
        Friend Shared ReadOnly Property TS70030I() As String
            Get
                Return ResourceManager.GetString("TS70030I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier auprès du demandeur si l&apos;employé doit conserver les accès communs à tous les employés des unités {0} même si aucun rôle pour ces unités ne sera assigné à l&apos;employé. Dans la négative, retirer les REO correspondant..
        '''</summary>
        Friend Shared ReadOnly Property TS70031I() As String
            Get
                Return ResourceManager.GetString("TS70031I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous pouvez sélectionner un maximum de 5 unités administratives seulement..
        '''</summary>
        Friend Shared ReadOnly Property TS70032E() As String
            Get
                Return ResourceManager.GetString("TS70032E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le retrait d&apos;un rôle prend effet à la date effective de la demande alors que la prolongation permet de conserver le rôle au-delà de cette date.  L&apos;action &quot;Retirer&quot; a eu préséance.  Corrigez au besoin..
        '''</summary>
        Friend Shared ReadOnly Property TS70033I() As String
            Get
                Return ResourceManager.GetString("TS70033I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous devez sélectionner entre 1 et 5 unités administratives.
        '''</summary>
        Friend Shared ReadOnly Property TS70034E() As String
            Get
                Return ResourceManager.GetString("TS70034E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez noter qu&apos;il peut s&apos;écouler un délai pouvant aller jusqu&apos;à une journée ouvrable, suivant la confirmation de réalisation par le CASI, avant que les modifications apportées aux rôles de l&apos;employé soient reflétées dans les tableaux d&apos;assignations..
        '''</summary>
        Friend Shared ReadOnly Property TS70035I() As String
            Get
                Return ResourceManager.GetString("TS70035I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;employé sera laissé sans rôle à l&apos;atteinte de la date de prolongation la plus lointaine.  Veuillez réviser ou inscrire un commentaire à la section Accès non couverts par les rôles..
        '''</summary>
        Friend Shared ReadOnly Property TS70036E() As String
            Get
                Return ResourceManager.GetString("TS70036E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection de {0} est incohérente avec {1}..
        '''</summary>
        Friend Shared ReadOnly Property TS70037E() As String
            Get
                Return ResourceManager.GetString("TS70037E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection de {0} nécessite la sélection de {1}..
        '''</summary>
        Friend Shared ReadOnly Property TS70038E() As String
            Get
                Return ResourceManager.GetString("TS70038E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection de {0} nécessite la sélection d&apos;un et un seul des rôles identifiés..
        '''</summary>
        Friend Shared ReadOnly Property TS70039E() As String
            Get
                Return ResourceManager.GetString("TS70039E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sélection de {0} nécessite la sélection d&apos;au moins un des rôles identifiés..
        '''</summary>
        Friend Shared ReadOnly Property TS70040E() As String
            Get
                Return ResourceManager.GetString("TS70040E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;employé détient au moins un &lt;b&gt;Compte supplémentaire&lt;/b&gt;..
        '''</summary>
        Friend Shared ReadOnly Property TS70042A() As String
            Get
                Return ResourceManager.GetString("TS70042A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Votre sélection (CR : {0} ) excède la capacité du système. Veuillez réduire le nombre d&apos;unités administratives sélectionnées..
        '''</summary>
        Friend Shared ReadOnly Property TS70042E() As String
            Get
                Return ResourceManager.GetString("TS70042E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Votre sélection (CR : {0} ) excède la capacité du système. Veuillez signaler un problème au CASI..
        '''</summary>
        Friend Shared ReadOnly Property TS70043E() As String
            Get
                Return ResourceManager.GetString("TS70043E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La conservation du ou des comptes supplémentaires suivants: {0} nécessite une confirmation du demandeur..
        '''</summary>
        Friend Shared ReadOnly Property TS70043I() As String
            Get
                Return ResourceManager.GetString("TS70043I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirmer auprès du demandeur que l&apos;employé doit conserver les comptes supplémentaires suivants : {0}..
        '''</summary>
        Friend Shared ReadOnly Property TS70044I() As String
            Get
                Return ResourceManager.GetString("TS70044I", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
