'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace portailsage3
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SageDiffServiceSoap", [Namespace]:="http://eurekify.com/webservices")>  _
    Partial Public Class SageDiffService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private diff_get_allOperationCompleted As System.Threading.SendOrPostCallback
        
        Private users_get_addedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private users_get_removedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private roles_get_addedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private roles_get_removedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private resources_get_addedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private resources_get_removedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_added_user_roleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_removed_user_roleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_added_user_resourceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_removed_user_resourceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_added_role_resourceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_removed_role_resourceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_added_role_roleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private links_get_removed_role_roleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auditcards_get_added_alertsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auditcards_get_removed_alertsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auditcards_get_alerts_status_updatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Rrq.Securite.GestionAcces.My.MySettings.Default.TS7N242_AccesSage_portailsage3_SageDiffService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event diff_get_allCompleted As diff_get_allCompletedEventHandler
        
        '''<remarks/>
        Public Event users_get_addedCompleted As users_get_addedCompletedEventHandler
        
        '''<remarks/>
        Public Event users_get_removedCompleted As users_get_removedCompletedEventHandler
        
        '''<remarks/>
        Public Event roles_get_addedCompleted As roles_get_addedCompletedEventHandler
        
        '''<remarks/>
        Public Event roles_get_removedCompleted As roles_get_removedCompletedEventHandler
        
        '''<remarks/>
        Public Event resources_get_addedCompleted As resources_get_addedCompletedEventHandler
        
        '''<remarks/>
        Public Event resources_get_removedCompleted As resources_get_removedCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_added_user_roleCompleted As links_get_added_user_roleCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_removed_user_roleCompleted As links_get_removed_user_roleCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_added_user_resourceCompleted As links_get_added_user_resourceCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_removed_user_resourceCompleted As links_get_removed_user_resourceCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_added_role_resourceCompleted As links_get_added_role_resourceCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_removed_role_resourceCompleted As links_get_removed_role_resourceCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_added_role_roleCompleted As links_get_added_role_roleCompletedEventHandler
        
        '''<remarks/>
        Public Event links_get_removed_role_roleCompleted As links_get_removed_role_roleCompletedEventHandler
        
        '''<remarks/>
        Public Event auditcards_get_added_alertsCompleted As auditcards_get_added_alertsCompletedEventHandler
        
        '''<remarks/>
        Public Event auditcards_get_removed_alertsCompleted As auditcards_get_removed_alertsCompletedEventHandler
        
        '''<remarks/>
        Public Event auditcards_get_alerts_status_updatesCompleted As auditcards_get_alerts_status_updatesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/diff_get_all", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function diff_get_all(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("diff_get_all", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub diff_get_allAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.diff_get_allAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub diff_get_allAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.diff_get_allOperationCompleted Is Nothing) Then
                Me.diff_get_allOperationCompleted = AddressOf Me.Ondiff_get_allOperationCompleted
            End If
            Me.InvokeAsync("diff_get_all", New Object() {server, database, oldCfg, updatedCfg}, Me.diff_get_allOperationCompleted, userState)
        End Sub
        
        Private Sub Ondiff_get_allOperationCompleted(ByVal arg As Object)
            If (Not (Me.diff_get_allCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent diff_get_allCompleted(Me, New diff_get_allCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/users_get_added", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function users_get_added(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("users_get_added", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub users_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.users_get_addedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub users_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.users_get_addedOperationCompleted Is Nothing) Then
                Me.users_get_addedOperationCompleted = AddressOf Me.Onusers_get_addedOperationCompleted
            End If
            Me.InvokeAsync("users_get_added", New Object() {server, database, oldCfg, updatedCfg}, Me.users_get_addedOperationCompleted, userState)
        End Sub
        
        Private Sub Onusers_get_addedOperationCompleted(ByVal arg As Object)
            If (Not (Me.users_get_addedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent users_get_addedCompleted(Me, New users_get_addedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/users_get_removed", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function users_get_removed(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("users_get_removed", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub users_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.users_get_removedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub users_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.users_get_removedOperationCompleted Is Nothing) Then
                Me.users_get_removedOperationCompleted = AddressOf Me.Onusers_get_removedOperationCompleted
            End If
            Me.InvokeAsync("users_get_removed", New Object() {server, database, oldCfg, updatedCfg}, Me.users_get_removedOperationCompleted, userState)
        End Sub
        
        Private Sub Onusers_get_removedOperationCompleted(ByVal arg As Object)
            If (Not (Me.users_get_removedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent users_get_removedCompleted(Me, New users_get_removedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/roles_get_added", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function roles_get_added(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("roles_get_added", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub roles_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.roles_get_addedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub roles_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.roles_get_addedOperationCompleted Is Nothing) Then
                Me.roles_get_addedOperationCompleted = AddressOf Me.Onroles_get_addedOperationCompleted
            End If
            Me.InvokeAsync("roles_get_added", New Object() {server, database, oldCfg, updatedCfg}, Me.roles_get_addedOperationCompleted, userState)
        End Sub
        
        Private Sub Onroles_get_addedOperationCompleted(ByVal arg As Object)
            If (Not (Me.roles_get_addedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent roles_get_addedCompleted(Me, New roles_get_addedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/roles_get_removed", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function roles_get_removed(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("roles_get_removed", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub roles_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.roles_get_removedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub roles_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.roles_get_removedOperationCompleted Is Nothing) Then
                Me.roles_get_removedOperationCompleted = AddressOf Me.Onroles_get_removedOperationCompleted
            End If
            Me.InvokeAsync("roles_get_removed", New Object() {server, database, oldCfg, updatedCfg}, Me.roles_get_removedOperationCompleted, userState)
        End Sub
        
        Private Sub Onroles_get_removedOperationCompleted(ByVal arg As Object)
            If (Not (Me.roles_get_removedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent roles_get_removedCompleted(Me, New roles_get_removedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/resources_get_added", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function resources_get_added(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("resources_get_added", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub resources_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.resources_get_addedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub resources_get_addedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.resources_get_addedOperationCompleted Is Nothing) Then
                Me.resources_get_addedOperationCompleted = AddressOf Me.Onresources_get_addedOperationCompleted
            End If
            Me.InvokeAsync("resources_get_added", New Object() {server, database, oldCfg, updatedCfg}, Me.resources_get_addedOperationCompleted, userState)
        End Sub
        
        Private Sub Onresources_get_addedOperationCompleted(ByVal arg As Object)
            If (Not (Me.resources_get_addedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent resources_get_addedCompleted(Me, New resources_get_addedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/resources_get_removed", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function resources_get_removed(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("resources_get_removed", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub resources_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.resources_get_removedAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub resources_get_removedAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.resources_get_removedOperationCompleted Is Nothing) Then
                Me.resources_get_removedOperationCompleted = AddressOf Me.Onresources_get_removedOperationCompleted
            End If
            Me.InvokeAsync("resources_get_removed", New Object() {server, database, oldCfg, updatedCfg}, Me.resources_get_removedOperationCompleted, userState)
        End Sub
        
        Private Sub Onresources_get_removedOperationCompleted(ByVal arg As Object)
            If (Not (Me.resources_get_removedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent resources_get_removedCompleted(Me, New resources_get_removedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_added_user_role", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_added_user_role(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_added_user_role", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_added_user_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_added_user_roleAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_added_user_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_added_user_roleOperationCompleted Is Nothing) Then
                Me.links_get_added_user_roleOperationCompleted = AddressOf Me.Onlinks_get_added_user_roleOperationCompleted
            End If
            Me.InvokeAsync("links_get_added_user_role", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_added_user_roleOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_added_user_roleOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_added_user_roleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_added_user_roleCompleted(Me, New links_get_added_user_roleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_removed_user_role", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_removed_user_role(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_removed_user_role", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_user_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_removed_user_roleAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_user_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_removed_user_roleOperationCompleted Is Nothing) Then
                Me.links_get_removed_user_roleOperationCompleted = AddressOf Me.Onlinks_get_removed_user_roleOperationCompleted
            End If
            Me.InvokeAsync("links_get_removed_user_role", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_removed_user_roleOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_removed_user_roleOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_removed_user_roleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_removed_user_roleCompleted(Me, New links_get_removed_user_roleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_added_user_resource", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_added_user_resource(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_added_user_resource", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_added_user_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_added_user_resourceAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_added_user_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_added_user_resourceOperationCompleted Is Nothing) Then
                Me.links_get_added_user_resourceOperationCompleted = AddressOf Me.Onlinks_get_added_user_resourceOperationCompleted
            End If
            Me.InvokeAsync("links_get_added_user_resource", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_added_user_resourceOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_added_user_resourceOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_added_user_resourceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_added_user_resourceCompleted(Me, New links_get_added_user_resourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_removed_user_resource", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_removed_user_resource(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_removed_user_resource", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_user_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_removed_user_resourceAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_user_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_removed_user_resourceOperationCompleted Is Nothing) Then
                Me.links_get_removed_user_resourceOperationCompleted = AddressOf Me.Onlinks_get_removed_user_resourceOperationCompleted
            End If
            Me.InvokeAsync("links_get_removed_user_resource", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_removed_user_resourceOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_removed_user_resourceOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_removed_user_resourceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_removed_user_resourceCompleted(Me, New links_get_removed_user_resourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_added_role_resource", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_added_role_resource(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_added_role_resource", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_added_role_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_added_role_resourceAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_added_role_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_added_role_resourceOperationCompleted Is Nothing) Then
                Me.links_get_added_role_resourceOperationCompleted = AddressOf Me.Onlinks_get_added_role_resourceOperationCompleted
            End If
            Me.InvokeAsync("links_get_added_role_resource", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_added_role_resourceOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_added_role_resourceOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_added_role_resourceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_added_role_resourceCompleted(Me, New links_get_added_role_resourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_removed_role_resource", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_removed_role_resource(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_removed_role_resource", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_role_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_removed_role_resourceAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_role_resourceAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_removed_role_resourceOperationCompleted Is Nothing) Then
                Me.links_get_removed_role_resourceOperationCompleted = AddressOf Me.Onlinks_get_removed_role_resourceOperationCompleted
            End If
            Me.InvokeAsync("links_get_removed_role_resource", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_removed_role_resourceOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_removed_role_resourceOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_removed_role_resourceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_removed_role_resourceCompleted(Me, New links_get_removed_role_resourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_added_role_role", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_added_role_role(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_added_role_role", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_added_role_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_added_role_roleAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_added_role_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_added_role_roleOperationCompleted Is Nothing) Then
                Me.links_get_added_role_roleOperationCompleted = AddressOf Me.Onlinks_get_added_role_roleOperationCompleted
            End If
            Me.InvokeAsync("links_get_added_role_role", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_added_role_roleOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_added_role_roleOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_added_role_roleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_added_role_roleCompleted(Me, New links_get_added_role_roleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/links_get_removed_role_role", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function links_get_removed_role_role(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String) As String
            Dim results() As Object = Me.Invoke("links_get_removed_role_role", New Object() {server, database, oldCfg, updatedCfg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_role_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String)
            Me.links_get_removed_role_roleAsync(server, database, oldCfg, updatedCfg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub links_get_removed_role_roleAsync(ByVal server As String, ByVal database As String, ByVal oldCfg As String, ByVal updatedCfg As String, ByVal userState As Object)
            If (Me.links_get_removed_role_roleOperationCompleted Is Nothing) Then
                Me.links_get_removed_role_roleOperationCompleted = AddressOf Me.Onlinks_get_removed_role_roleOperationCompleted
            End If
            Me.InvokeAsync("links_get_removed_role_role", New Object() {server, database, oldCfg, updatedCfg}, Me.links_get_removed_role_roleOperationCompleted, userState)
        End Sub
        
        Private Sub Onlinks_get_removed_role_roleOperationCompleted(ByVal arg As Object)
            If (Not (Me.links_get_removed_role_roleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent links_get_removed_role_roleCompleted(Me, New links_get_removed_role_roleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/auditcards_get_added_alerts", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auditcards_get_added_alerts(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String) As String
            Dim results() As Object = Me.Invoke("auditcards_get_added_alerts", New Object() {server, database, oldAud, updatedAud})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_added_alertsAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String)
            Me.auditcards_get_added_alertsAsync(server, database, oldAud, updatedAud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_added_alertsAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String, ByVal userState As Object)
            If (Me.auditcards_get_added_alertsOperationCompleted Is Nothing) Then
                Me.auditcards_get_added_alertsOperationCompleted = AddressOf Me.Onauditcards_get_added_alertsOperationCompleted
            End If
            Me.InvokeAsync("auditcards_get_added_alerts", New Object() {server, database, oldAud, updatedAud}, Me.auditcards_get_added_alertsOperationCompleted, userState)
        End Sub
        
        Private Sub Onauditcards_get_added_alertsOperationCompleted(ByVal arg As Object)
            If (Not (Me.auditcards_get_added_alertsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auditcards_get_added_alertsCompleted(Me, New auditcards_get_added_alertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/auditcards_get_removed_alerts", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auditcards_get_removed_alerts(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String) As String
            Dim results() As Object = Me.Invoke("auditcards_get_removed_alerts", New Object() {server, database, oldAud, updatedAud})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_removed_alertsAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String)
            Me.auditcards_get_removed_alertsAsync(server, database, oldAud, updatedAud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_removed_alertsAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String, ByVal userState As Object)
            If (Me.auditcards_get_removed_alertsOperationCompleted Is Nothing) Then
                Me.auditcards_get_removed_alertsOperationCompleted = AddressOf Me.Onauditcards_get_removed_alertsOperationCompleted
            End If
            Me.InvokeAsync("auditcards_get_removed_alerts", New Object() {server, database, oldAud, updatedAud}, Me.auditcards_get_removed_alertsOperationCompleted, userState)
        End Sub
        
        Private Sub Onauditcards_get_removed_alertsOperationCompleted(ByVal arg As Object)
            If (Not (Me.auditcards_get_removed_alertsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auditcards_get_removed_alertsCompleted(Me, New auditcards_get_removed_alertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eurekify.com/webservices/auditcards_get_alerts_status_updates", RequestNamespace:="http://eurekify.com/webservices", ResponseNamespace:="http://eurekify.com/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auditcards_get_alerts_status_updates(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String) As String
            Dim results() As Object = Me.Invoke("auditcards_get_alerts_status_updates", New Object() {server, database, oldAud, updatedAud})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_alerts_status_updatesAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String)
            Me.auditcards_get_alerts_status_updatesAsync(server, database, oldAud, updatedAud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auditcards_get_alerts_status_updatesAsync(ByVal server As String, ByVal database As String, ByVal oldAud As String, ByVal updatedAud As String, ByVal userState As Object)
            If (Me.auditcards_get_alerts_status_updatesOperationCompleted Is Nothing) Then
                Me.auditcards_get_alerts_status_updatesOperationCompleted = AddressOf Me.Onauditcards_get_alerts_status_updatesOperationCompleted
            End If
            Me.InvokeAsync("auditcards_get_alerts_status_updates", New Object() {server, database, oldAud, updatedAud}, Me.auditcards_get_alerts_status_updatesOperationCompleted, userState)
        End Sub
        
        Private Sub Onauditcards_get_alerts_status_updatesOperationCompleted(ByVal arg As Object)
            If (Not (Me.auditcards_get_alerts_status_updatesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auditcards_get_alerts_status_updatesCompleted(Me, New auditcards_get_alerts_status_updatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub diff_get_allCompletedEventHandler(ByVal sender As Object, ByVal e As diff_get_allCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class diff_get_allCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub users_get_addedCompletedEventHandler(ByVal sender As Object, ByVal e As users_get_addedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class users_get_addedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub users_get_removedCompletedEventHandler(ByVal sender As Object, ByVal e As users_get_removedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class users_get_removedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub roles_get_addedCompletedEventHandler(ByVal sender As Object, ByVal e As roles_get_addedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class roles_get_addedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub roles_get_removedCompletedEventHandler(ByVal sender As Object, ByVal e As roles_get_removedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class roles_get_removedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub resources_get_addedCompletedEventHandler(ByVal sender As Object, ByVal e As resources_get_addedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class resources_get_addedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub resources_get_removedCompletedEventHandler(ByVal sender As Object, ByVal e As resources_get_removedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class resources_get_removedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_added_user_roleCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_added_user_roleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_added_user_roleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_removed_user_roleCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_removed_user_roleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_removed_user_roleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_added_user_resourceCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_added_user_resourceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_added_user_resourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_removed_user_resourceCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_removed_user_resourceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_removed_user_resourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_added_role_resourceCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_added_role_resourceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_added_role_resourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_removed_role_resourceCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_removed_role_resourceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_removed_role_resourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_added_role_roleCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_added_role_roleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_added_role_roleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub links_get_removed_role_roleCompletedEventHandler(ByVal sender As Object, ByVal e As links_get_removed_role_roleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class links_get_removed_role_roleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub auditcards_get_added_alertsCompletedEventHandler(ByVal sender As Object, ByVal e As auditcards_get_added_alertsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auditcards_get_added_alertsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub auditcards_get_removed_alertsCompletedEventHandler(ByVal sender As Object, ByVal e As auditcards_get_removed_alertsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auditcards_get_removed_alertsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub auditcards_get_alerts_status_updatesCompletedEventHandler(ByVal sender As Object, ByVal e As auditcards_get_alerts_status_updatesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auditcards_get_alerts_status_updatesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
