'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.3603
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Namespace SageDNAService

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dna.eurekify.com", ConfigurationName:="SageDNAServicePortType")> _
    Public Interface SageDNAServicePortType

        'CODEGEN : Le paramètre « in2 » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlArrayAttribute ».
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Function fixAlertsNoBlock(ByVal request As fixAlertsNoBlockRequest) As fixAlertsNoBlockResponse

        'CODEGEN : Le paramètre « in2 » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlArrayAttribute ».
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Function fixAlerts(ByVal request As fixAlertsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> fixAlertsResponse

        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Sub clearCaches()

        'CODEGEN : Le paramètre « in3 » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlElementAttribute ».
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Function fixAlert(ByVal request As fixAlertRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> fixAlertResponse

        'CODEGEN : Le paramètre « out » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlElementAttribute ».
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Function getConnectionDetails(ByVal request As getConnectionDetailsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> getConnectionDetailsResponse

        'CODEGEN : Le paramètre « out » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlArrayAttribute ».
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute()> _
        Function getAuditTypesWithActions(ByVal request As getAuditTypesWithActionsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> getAuditTypesWithActionsResponse
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlertsNoBlock", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertsNoBlockRequest

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0)> _
        Public in0 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=1)> _
        Public in1 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=2), _
         System.Xml.Serialization.XmlArrayAttribute(IsNullable:=True)> _
        Public in2() As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=3), _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public in3 As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2() As Integer, ByVal in3 As String)
            MyBase.New()
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
            Me.in3 = in3
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlertsNoBlockResponse", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertsNoBlockResponse

        Public Sub New()
            MyBase.New()
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlerts", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertsRequest

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0)> _
        Public in0 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=1)> _
        Public in1 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=2), _
         System.Xml.Serialization.XmlArrayAttribute(IsNullable:=True)> _
        Public in2() As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=3), _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public in3 As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2() As Integer, ByVal in3 As String)
            MyBase.New()
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
            Me.in3 = in3
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlertsResponse", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertsResponse

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0)> _
        Public out As Boolean

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal out As Boolean)
            MyBase.New()
            Me.out = out
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlert", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertRequest

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0)> _
        Public in0 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=1)> _
        Public in1 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=2)> _
        Public in2 As Integer

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=3), _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public in3 As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2 As Integer, ByVal in3 As String)
            MyBase.New()
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
            Me.in3 = in3
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fixAlertResponse", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class fixAlertResponse

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0)> _
        Public out As Boolean

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal out As Boolean)
            MyBase.New()
            Me.out = out
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dna.eurekify.com")> _
    Partial Public Class ConnectionDetails

        Private databaseField As String

        Private integratedSecurityField As Boolean

        Private integratedSecurityFieldSpecified As Boolean

        Private passwordField As String

        Private serverField As String

        Private usernameField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=0)> _
        Public Property database() As String
            Get
                Return Me.databaseField
            End Get
            Set(ByVal value As String)
                Me.databaseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property integratedSecurity() As Boolean
            Get
                Return Me.integratedSecurityField
            End Get
            Set(ByVal value As Boolean)
                Me.integratedSecurityField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property integratedSecuritySpecified() As Boolean
            Get
                Return Me.integratedSecurityFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.integratedSecurityFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set(ByVal value As String)
                Me.passwordField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=3)> _
        Public Property server() As String
            Get
                Return Me.serverField
            End Get
            Set(ByVal value As String)
                Me.serverField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=4)> _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set(ByVal value As String)
                Me.usernameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dna.eurekify.com")> _
    Partial Public Class Action

        Private codeField As String

        Private descriptionField As String

        Private nameField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=0)> _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(ByVal value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=1)> _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set(ByVal value As String)
                Me.descriptionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dna.eurekify.com")> _
    Partial Public Class AuditType

        Private actionsField() As Action

        Private idField As Integer

        Private idFieldSpecified As Boolean

        Private nameField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=True, Order:=0)> _
        Public Property actions() As Action()
            Get
                Return Me.actionsField
            End Get
            Set(ByVal value As Action())
                Me.actionsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set(ByVal value As Integer)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property idSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.idFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getConnectionDetails", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class getConnectionDetailsRequest

        Public Sub New()
            MyBase.New()
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getConnectionDetailsResponse", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class getConnectionDetailsResponse

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0), _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public out As ConnectionDetails

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal out As ConnectionDetails)
            MyBase.New()
            Me.out = out
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAuditTypesWithActions", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class getAuditTypesWithActionsRequest

        Public Sub New()
            MyBase.New()
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAuditTypesWithActionsResponse", WrapperNamespace:="http://dna.eurekify.com", IsWrapped:=True)> _
    Partial Public Class getAuditTypesWithActionsResponse

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dna.eurekify.com", Order:=0), _
         System.Xml.Serialization.XmlArrayAttribute(IsNullable:=True)> _
        Public out() As AuditType

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal out() As AuditType)
            MyBase.New()
            Me.out = out
        End Sub
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface SageDNAServicePortTypeChannel
        Inherits SageDNAServicePortType, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Partial Public Class SageDNAServicePortTypeClient
        Inherits System.ServiceModel.ClientBase(Of SageDNAServicePortType)
        Implements SageDNAServicePortType

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function SageDNAServicePortType_fixAlertsNoBlock(ByVal request As fixAlertsNoBlockRequest) As fixAlertsNoBlockResponse Implements SageDNAServicePortType.fixAlertsNoBlock
            Return MyBase.Channel.fixAlertsNoBlock(request)
        End Function

        Public Sub fixAlertsNoBlock(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2() As Integer, ByVal in3 As String)
            Dim inValue As fixAlertsNoBlockRequest = New fixAlertsNoBlockRequest
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            inValue.in3 = in3
            Dim retVal As fixAlertsNoBlockResponse = CType(Me, SageDNAServicePortType).fixAlertsNoBlock(inValue)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function SageDNAServicePortType_fixAlerts(ByVal request As fixAlertsRequest) As fixAlertsResponse Implements SageDNAServicePortType.fixAlerts
            Return MyBase.Channel.fixAlerts(request)
        End Function

        Public Function fixAlerts(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2() As Integer, ByVal in3 As String) As Boolean
            Dim inValue As fixAlertsRequest = New fixAlertsRequest
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            inValue.in3 = in3
            Dim retVal As fixAlertsResponse = CType(Me, SageDNAServicePortType).fixAlerts(inValue)
            Return retVal.out
        End Function

        Public Sub clearCaches() Implements SageDNAServicePortType.clearCaches
            MyBase.Channel.clearCaches()
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function SageDNAServicePortType_fixAlert(ByVal request As fixAlertRequest) As fixAlertResponse Implements SageDNAServicePortType.fixAlert
            Return MyBase.Channel.fixAlert(request)
        End Function

        Public Function fixAlert(ByVal in0 As Integer, ByVal in1 As Integer, ByVal in2 As Integer, ByVal in3 As String) As Boolean
            Dim inValue As fixAlertRequest = New fixAlertRequest
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            inValue.in3 = in3
            Dim retVal As fixAlertResponse = CType(Me, SageDNAServicePortType).fixAlert(inValue)
            Return retVal.out
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function SageDNAServicePortType_getConnectionDetails(ByVal request As getConnectionDetailsRequest) As getConnectionDetailsResponse Implements SageDNAServicePortType.getConnectionDetails
            Return MyBase.Channel.getConnectionDetails(request)
        End Function

        Public Function getConnectionDetails() As ConnectionDetails
            Dim inValue As getConnectionDetailsRequest = New getConnectionDetailsRequest
            Dim retVal As getConnectionDetailsResponse = CType(Me, SageDNAServicePortType).getConnectionDetails(inValue)
            Return retVal.out
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function SageDNAServicePortType_getAuditTypesWithActions(ByVal request As getAuditTypesWithActionsRequest) As getAuditTypesWithActionsResponse Implements SageDNAServicePortType.getAuditTypesWithActions
            Return MyBase.Channel.getAuditTypesWithActions(request)
        End Function

        Public Function getAuditTypesWithActions() As AuditType()
            Dim inValue As getAuditTypesWithActionsRequest = New getAuditTypesWithActionsRequest
            Dim retVal As getAuditTypesWithActionsResponse = CType(Me, SageDNAServicePortType).getAuditTypesWithActions(inValue)
            Return retVal.out
        End Function
    End Class
End Namespace
